# Generated by Django 4.2.6 on 2023-10-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rail_coder", "0002_document_source_document_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="domain",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
