# Generated by Django 4.2.6 on 2023-10-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rail_coder", "0003_document_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentcode",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
