# Generated by Django 4.2.6 on 2023-10-11 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("rail_coder", "0004_documentcode_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentcode",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
